<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\District;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $districts = [
            ["id" => "1", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-حصاربوعلی"],
            ["id" => "2", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-رستم آباد- فرمانیه"],
            ["id" => "3", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-اوین"],
            ["id" => "4", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-درکه"],
            ["id" => "5", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-زعفرانیه"],
            ["id" => "6", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-محمودیه"],
            ["id" => "7", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-ولنجک"],
            ["id" => "8", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-امام زاده قاسم (ع)"],
            ["id" => "9", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-دربند"],
            ["id" => "10", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-گلابدره"],
            ["id" => "11", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-جماران"],
            ["id" => "12", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-دزاشیب"],
            ["id" => "13", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-نیاوران"],
            ["id" => "14", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-اراج"],
            ["id" => "15", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-کاشانک"],
            ["id" => "16", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-شهرک دانشگاه"],
            ["id" => "17", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-شهرک نفت"],
            ["id" => "18", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-دارآباد"],
            ["id" => "19", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-باغ فردوس"],
            ["id" => "20", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-تجریش"],
            ["id" => "21", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-قیطریه"],
            ["id" => "22", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-چیذر"],
            ["id" => "23", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-حکمت"],
            ["id" => "24", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-ازگل"],
            ["id" => "25", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-سوهانک"],
            ["id" => "26", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-شهید محلاتی"],
            ["id" => "27", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-اتوبان امام علی"],
            ["id" => "28", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-اتوبان صدر"],
            ["id" => "29", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-اقدسیه"],
            ["id" => "30", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-الهیه - فرشته"],
            ["id" => "31", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-اندرزگو"],
            ["id" => "32", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-بلوار ارتش"],
            ["id" => "33", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-پارک وی"],
            ["id" => "34", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-تجریش"],
            ["id" => "35", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-جمشیدیه"],
            ["id" => "36", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-دیباجی"],
            ["id" => "37", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-سعدآباد"],
            ["id" => "38", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-صاحبقرانیه"],
            ["id" => "39", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-فرمانیه"],
            ["id" => "40", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-قیطریه"],
            ["id" => "41", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-محمودیه"],
            ["id" => "42", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-مقدس اردبیلی"],
            ["id" => "43", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-مینی سیتی"],
            ["id" => "44", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-نوبنیاد"],
            ["id" => "45", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-ولیعصر"],
            ["id" => "46", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-کاشانک"],
            ["id" => "47", "province_id" => 8, "city_id" => 126, "name" => "منطقه۱-کامرانیه"],
            ["id" => "48", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-بوعلی"],
            ["id" => "49", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-سعادت آباد"],
            ["id" => "50", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-مدیریت"],
            ["id" => "51", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-کوهسار"],
            ["id" => "52", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-پونک"],
            ["id" => "53", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-شهید چوب تراش"],
            ["id" => "54", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-شهید خرم رودی"],
            ["id" => "55", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-صادقیه شمالی شهرک هما"],
            ["id" => "56", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-صادقیه"],
            ["id" => "57", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-شهرآرا"],
            ["id" => "58", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-کوی نصر"],
            ["id" => "59", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-پردیسان"],
            ["id" => "60", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-شهرک آزمایش"],
            ["id" => "61", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-تهران ویلا"],
            ["id" => "62", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-برق آلستوم"],
            ["id" => "63", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-تیموری"],
            ["id" => "64", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-طرشت"],
            ["id" => "65", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-همایونشهر"],
            ["id" => "66", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-توحید"],
            ["id" => "67", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-زنجان"],
            ["id" => "68", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-شادمهر"],
            ["id" => "69", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-ایوانک"],
            ["id" => "70", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-دریا"],
            ["id" => "71", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-شهرک قدس"],
            ["id" => "72", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-آسمانها"],
            ["id" => "73", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-درختی"],
            ["id" => "74", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-فرحزاد"],
            ["id" => "75", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-مخابرات"],
            ["id" => "76", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-پرواز"],
            ["id" => "77", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-آزادی"],
            ["id" => "78", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-اتوبان حکیم"],
            ["id" => "79", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-اتوبان شیخ فضل اله نوری"],
            ["id" => "80", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-اتوبان محمد علی جناح"],
            ["id" => "81", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-اتوبان نیایش"],
            ["id" => "82", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-اتوبان یادگار امام"],
            ["id" => "83", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-بهبودی"],
            ["id" => "84", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-جلال آل احمد"],
            ["id" => "85", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-خوش شمالی"],
            ["id" => "86", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-ستارخان"],
            ["id" => "87", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-شادمان"],
            ["id" => "88", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-شهرک ژاندارمری"],
            ["id" => "89", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-شهرک غرب"],
            ["id" => "90", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-گیشا"],
            ["id" => "91", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-مترو شریف"],
            ["id" => "92", "province_id" => 8, "city_id" => 126, "name" => "منطقه۲-مرزداران"],
            ["id" => "93", "province_id" => 8, "city_id" => 126, "name" => "منطقه۳-آرارات"],
            ["id" => "94", "province_id" => 8, "city_id" => 126, "name" => "منطقه۳-ونک"],
            ["id" => "95", "province_id" => 8, "city_id" => 126, "name" => "منطقه۳-امانیه"],
            ["id" => "96", "province_id" => 8, "city_id" => 126, "name" => "منطقه۳-زرگنده"],
            ["id" => "97", "province_id" => 8, "city_id" => 126, "name" => "منطقه۳-درب دوم"],
            ["id" => "98", "province_id" => 8, "city_id" => 126, "name" => "منطقه۳-رستم آباد و اختیاریه"],
            ["id" => "99", "province_id" => 8, "city_id" => 126, "name" => "منطقه۳-داودیه"],
            ["id" => "100", "province_id" => 8, "city_id" => 126, "name" => "منطقه۳-سید خندان"],
            ["id" => "101", "province_id" => 8, "city_id" => 126, "name" => "منطقه۳-دروس
            "],
            ["id" => "102", "province_id" => 8, "city_id" => 126, "name" => "منطقه۳-قبا"],
            ["id" => "103", "province_id" => 8, "city_id" => 126, "name" => "منطقه۳-قلهک"],
            ["id" => "104", "province_id" => 8, "city_id" => 126, "name" => "منطقه۳-کاوسیه"],
            ["id" => "105", "province_id" => 8, "city_id" => 126, "name" => "منطقه۳-اختیاریه"],
            ["id" => "106", "province_id" => 8, "city_id" => 126, "name" => "منطقه۳-پاسداران"],
            ["id" => "107", "province_id" => 8, "city_id" => 126, "name" => "منطقه۳-جردن"],
            ["id" => "108", "province_id" => 8, "city_id" => 126, "name" => "منطقه۳-خواجه عبداله
            "],
            ["id" => "109", "province_id" => 8, "city_id" => 126, "name" => "منطقه۳-دولت ( کلاهدوز )"],
            ["id" => "110", "province_id" => 8, "city_id" => 126, "name" => "منطقه۳-شیخ بهایی"],
            ["id" => "111", "province_id" => 8, "city_id" => 126, "name" => "منطقه۳-شیراز"],
            ["id" => "112", "province_id" => 8, "city_id" => 126, "name" => "منطقه۳-ظفر"],
            ["id" => "113", "province_id" => 8, "city_id" => 126, "name" => "منطقه۳-ملاصدرا"],
            ["id" => "114", "province_id" => 8, "city_id" => 126, "name" => "منطقه۳-میدان کتابی"],
            ["id" => "115", "province_id" => 8, "city_id" => 126, "name" => "منطقه۳-میرداماد"],
            ["id" => "116", "province_id" => 8, "city_id" => 126, "name" => "منطقه۳-ولیعصر(بین پارک وی ونیایش)"],
            ["id" => "117", "province_id" => 8, "city_id" => 126, "name" => "منطقه۳-جلفا"],
            ["id" => "118", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-مهران"],
            ["id" => "119", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-کاظم آباد"],
            ["id" => "120", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-کوهک"],
            ["id" => "121", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-مجیدیه و شمس آباد"],
            ["id" => "122", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-پاسداران و ضرابخانه"],
            ["id" => "123", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-حسین آباد و مبارک آباد"],
            ["id" => "124", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-شیان و لویزان"],
            ["id" => "125", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-علم و صنعت"],
            ["id" => "126", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-نارمک"],
            ["id" => "127", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-تهرانپارس غربی"],
            ["id" => "128", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-جوادیه"],
            ["id" => "129", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-خاک سفید"],
            ["id" => "130", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-خاک سفید"],
            ["id" => "131", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-قاسم آباد و ده نارمک"],
            ["id" => "132", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-اوقاف"],
            ["id" => "133", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-شمیران نو"],
            ["id" => "134", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-حکیمیه"],
            ["id" => "135", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-قنات کوثر"],
            ["id" => "136", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-کوهسار"],
            ["id" => "137", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-مجید آباد"],
            ["id" => "138", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-اتوبان بابایی"],
            ["id" => "139", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-اتوبان باقری"],
            ["id" => "140", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-اتوبان صیاد شیرازی"],
            ["id" => "141", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-بنی هاشم"],
            ["id" => "142", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-پلیس
            "],
            ["id" => "143", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-دلاوران"],
            ["id" => "144", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-رسالت"],
            ["id" => "145", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-سراج"],
            ["id" => "146", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-شمس آباد"],
            ["id" => "147", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-شهدا"],
            ["id" => "148", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-صیاد شیرازی"],
            ["id" => "149", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-علم وصنعت"],
            ["id" => "150", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-فرجام"],
            ["id" => "151", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-لویزان"],
            ["id" => "152", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-میدان ملت"],
            ["id" => "153", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-هروی"],
            ["id" => "154", "province_id" => 8, "city_id" => 126, "name" => "منطقه۴-هنگام"],
            ["id" => "155", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-شهران جنوبی"],
            ["id" => "156", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-شهران شمالی"],
            ["id" => "157", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-شهرزیبا"],
            ["id" => "158", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-اندیشه"],
            ["id" => "159", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-بهاران"],
            ["id" => "160", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-کن"],
            ["id" => "161", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-المهدی"],
            ["id" => "162", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-باغ فیض"],
            ["id" => "163", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-پونک جنوبی"],
            ["id" => "164", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-پونک شمالی"],
            ["id" => "165", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-حصارک"],
            ["id" => "166", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-شهرک نفت"],
            ["id" => "167", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-کوهسار"],
            ["id" => "168", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-مرادآباد"],
            ["id" => "169", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-پرواز"],
            ["id" => "170", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-سازمان برنامه جنوبی"],
            ["id" => "171", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-سازمان برنامه شمالی"],
            ["id" => "172", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-ارم"],
            ["id" => "173", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-سازمان آب"],
            ["id" => "174", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-اباذر"],
            ["id" => "175", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-فردوس"],
            ["id" => "176", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-مهران"],
            ["id" => "177", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-اکباتان"],
            ["id" => "178", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-بیمه"],
            ["id" => "179", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-آپادانا"],
            ["id" => "180", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-جنت آباد جنوبی"],
            ["id" => "181", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-جنت آباد شمالی"],
            ["id" => "182", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-جنت آباد مرکزی"],
            ["id" => "183", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-شاهین"],
            ["id" => "184", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-آیت الله کاشانی"],
            ["id" => "185", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-اشرفی اصفهانی"],
            ["id" => "186", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-ایران زمین شمالی"],
            ["id" => "187", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-بلوار تعاون"],
            ["id" => "188", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-بلوار فردوس"],
            ["id" => "189", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-بولیوار"],
            ["id" => "190", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-پونک"],
            ["id" => "191", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-پیامبر"],
            ["id" => "192", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-جنت آباد"],
            ["id" => "193", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-سازمان برنامه"],
            ["id" => "194", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-ستاری"],
            ["id" => "195", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-سردار جنگل"],
            ["id" => "196", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-سولقان"],
            ["id" => "197", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-شهر زیبا"],
            ["id" => "198", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-شهران"],
            ["id" => "199", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-شهرک اکباتان"],
            ["id" => "200", "province_id" => 8, "city_id" => 126, "name" => "منطقه۵-شهید مهدی باکری"],
            ["id" => "201", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-نجات اللهی"],
            ["id" => "202", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-ایرانشهر"],
            ["id" => "203", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-پارک لاله"],
            ["id" => "204", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-کشاورز غربی"],
            ["id" => "205", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-نصرت"],
            ["id" => "206", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-16آذر"],
            ["id" => "207", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-سنایی"],
            ["id" => "208", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-بهجت آباد"],
            ["id" => "209", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-عباس آباد"],
            ["id" => "210", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-قزل قلعه"],
            ["id" => "211", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-سیندخت"],
            ["id" => "212", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-گلها"],
            ["id" => "213", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-شیراز جنوبی"],
            ["id" => "214", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-گاندی"],
            ["id" => "215", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-ساعی"],
            ["id" => "216", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-یوسف آباد"],
            ["id" => "217", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-جهاد"],
            ["id" => "218", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-جنت"],
            ["id" => "219", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-آرژانتین"],
            ["id" => "220", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-اتوبان همت"],
            ["id" => "221", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-اسکندری"],
            ["id" => "222", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-امیر آباد"],
            ["id" => "223", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-بلوار کشاورز"],
            ["id" => "224", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-توانیر"],
            ["id" => "225", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-جمال زاده"],
            ["id" => "226", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-حافظ"],
            ["id" => "227", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-زرتشت"],
            ["id" => "228", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-طالقانی"],
            ["id" => "229", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-فاطمی"],
            ["id" => "230", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-فلسطین"],
            ["id" => "231", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-میدان انقلاب اسلامی"],
            ["id" => "232", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-میدان ولیعصر"],
            ["id" => "233", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-وزراء"],
            ["id" => "234", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-کارگر شمالی"],
            ["id" => "235", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-کردستان"],
            ["id" => "236", "province_id" => 8, "city_id" => 126, "name" => "منطقه۶-کریم خان"],
            ["id" => "237", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-شارق الف"],
            ["id" => "238", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-دهقان"],
            ["id" => "239", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-شارق ب"],
            ["id" => "240", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-گرگان"],
            ["id" => "241", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-نظام آباد"],
            ["id" => "242", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-خواجه نصیر و حقوقی"],
            ["id" => "243", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-خواجه نظام شرقی"],
            ["id" => "244", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-خواجه نظام غربی"],
            ["id" => "245", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-کاج
            "],
            ["id" => "246", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-امجدیه خاقانی"],
            ["id" => "247", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-بهار"],
            ["id" => "248", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-سهروردی باغ صبا"],
            ["id" => "249", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-شهیدقندی- نیلوفر"],
            ["id" => "250", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-عباس آباد- اندیشه"],
            ["id" => "251", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-حشمتیه"],
            ["id" => "252", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-دبستان"],
            ["id" => "253", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-ارامنه الف"],
            ["id" => "254", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-ارامنه ب"],
            ["id" => "255", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-قصر"],
            ["id" => "256", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-آپادانا"],
            ["id" => "257", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-امام حسین"],
            ["id" => "258", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-انقلاب"],
            ["id" => "259", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-خواجه نظام"],
            ["id" => "260", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-سرباز"],
            ["id" => "261", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-سهروردی"],
            ["id" => "262", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-شریعتی"],
            ["id" => "263", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-شهید مدنی"],
            ["id" => "264", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-شیخ صفی"],
            ["id" => "265", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-عباس آباد"],
            ["id" => "266", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-مدنی"],
            ["id" => "267", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-مرودشت"],
            ["id" => "268", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-مطهری"],
            ["id" => "269", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-مفتح جنوبی"],
            ["id" => "270", "province_id" => 8, "city_id" => 126, "name" => "منطقه۷-هفت تیر"],
            ["id" => "271", "province_id" => 8, "city_id" => 126, "name" => "منطقه۸-تهرانپارس"],
            ["id" => "272", "province_id" => 8, "city_id" => 126, "name" => "منطقه۸-دردشت"],
            ["id" => "273", "province_id" => 8, "city_id" => 126, "name" => "منطقه۸-مدائن"],
            ["id" => "274", "province_id" => 8, "city_id" => 126, "name" => "منطقه۸-هفت حوض"],
            ["id" => "275", "province_id" => 8, "city_id" => 126, "name" => "منطقه۸-فدک"],
            ["id" => "276", "province_id" => 8, "city_id" => 126, "name" => "منطقه۸-زرکش"],
            ["id" => "277", "province_id" => 8, "city_id" => 126, "name" => "منطقه۸-نارمک"],
            ["id" => "278", "province_id" => 8, "city_id" => 126, "name" => "منطقه۸-مجیدیه"],
            ["id" => "279", "province_id" => 8, "city_id" => 126, "name" => "منطقه۸-کرمان"],
            ["id" => "280", "province_id" => 8, "city_id" => 126, "name" => "منطقه۸-لشگر شرقی"],
            ["id" => "281", "province_id" => 8, "city_id" => 126, "name" => "منطقه۸-لشگر غربی"],
            ["id" => "282", "province_id" => 8, "city_id" => 126, "name" => "منطقه۸-وحیدیه"],
            ["id" => "283", "province_id" => 8, "city_id" => 126, "name" => "منطقه۸-تسلیحات"],
            ["id" => "284", "province_id" => 8, "city_id" => 126, "name" => "منطقه۸-جشنواره"],
            ["id" => "285", "province_id" => 8, "city_id" => 126, "name" => "منطقه۸-سبلان"],
            ["id" => "286", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۹-دکتر هوشیار"],
            ["id" => "287", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۹-شهید دستغیب"],
            ["id" => "288", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۹-فتح
            "],
            ["id" => "289", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۹-امامزاده عبداله"],
            ["id" => "290", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۹-شمشیری"],
            ["id" => "291", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۹-سرآسیاب مهرآباد"],
            ["id" => "292", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۹-مهرآبادجنوبی"],
            ["id" => "293", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۹-استاد معین"],
            ["id" => "294", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۹-سی متری جی"],
            ["id" => "295", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۹-طوس"],
            ["id" => "296", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۹-مهر آباد جنوبی"],
            ["id" => "297", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۹-مهرآباد"],
            ["id" => "298", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۹-امامزاده عبدالله"],
            ["id" => "299", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۹-فتح - صنعتی"],
            ["id" => "300", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۰-بریانک"],
            ["id" => "301", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۰-سلیمانی تیموری"],
            ["id" => "302", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۰-شبیری جی"],
            ["id" => "303", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۰-هفت چنار"],
            ["id" => "304", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۰-سلسبیل جنوبی"],
            ["id" => "305", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۰-کارون جنوبی"],
            ["id" => "306", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۰-هاشمی"],
            ["id" => "307", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۰-زنجان جنوبی"],
            ["id" => "308", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۰-سلسبیل شمالی"],
            ["id" => "309", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۰-کارون شمالی"],
            ["id" => "310", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۰-آذربایجان"],
            ["id" => "311", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۰-آزادی"],
            ["id" => "312", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۰-امام خمینی"],
            ["id" => "313", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۰-جیحون"],
            ["id" => "314", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۰-حسام الدین"],
            ["id" => "315", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۰-خوش"],
            ["id" => "316", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۰-دامپزشکی"],
            ["id" => "317", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۰-رودکی"],
            ["id" => "318", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۰-سینا"],
            ["id" => "319", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۰-قصرالدشت"],
            ["id" => "320", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۰-مالک اشتر"],
            ["id" => "321", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۰-نواب"],
            ["id" => "322", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۰-کارون"],
            ["id" => "323", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۰-کمیل"],
            ["id" => "324", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۱-شیخ هادی"],
            ["id" => "325", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۱-انقلاب"],
            ["id" => "326", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۱-امیریه ( فرهنگ )"],
            ["id" => "327", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۱-فروزش"],
            ["id" => "328", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۱-قلمستان"],
            ["id" => "329", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۱-منیریه"],
            ["id" => "330", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۱-حشمت الدوله – جمالزاده"],
            ["id" => "331", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۱-اسکندری"],
            ["id" => "332", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۱-دخانیات"],
            ["id" => "333", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۱-مخصوص"],
            ["id" => "334", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۱-جمهوری"],
            ["id" => "335", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۱-حر"],
            ["id" => "336", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۱-انبار نفت"],
            ["id" => "337", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۱-آگاهی"],
            ["id" => "338", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۱-راه آهن"],
            ["id" => "339", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۱-عباسی"],
            ["id" => "340", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۱-هلال احمر"],
            ["id" => "341", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۱-ابوسعید"],
            ["id" => "342", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۱-اسکندری جنوبی"],
            ["id" => "343", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۱-پاستور"],
            ["id" => "344", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۱-حسن آباد"],
            ["id" => "345", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۱-گمرک"],
            ["id" => "346", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۱-وحدت اسلامی"],
            ["id" => "347", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۱-ولیعصر"],
            ["id" => "348", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۱-کارگر جنوبی"],
            ["id" => "349", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۱-کاشان"],
            ["id" => "350", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۲-بهارستان"],
            ["id" => "351", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۲-فردوسی"],
            ["id" => "352", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۲-امامزاده یحیی"],
            ["id" => "353", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۲-پامنار"],
            ["id" => "354", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۲-بازار"],
            ["id" => "355", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۲-سنگلج"],
            ["id" => "356", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۲-تختی"],
            ["id" => "357", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۲-هرندی"],
            ["id" => "358", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۲-آبشار"],
            ["id" => "359", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۲-قیام"],
            ["id" => "360", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۲-کوثر"],
            ["id" => "361", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۲-ایران"],
            ["id" => "362", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۲-دروازه شمیران"],
            ["id" => "363", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۲-امین حضور"],
            ["id" => "364", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۲-پانزده خرداد"],
            ["id" => "365", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۲-پیچ شمیران"],
            ["id" => "366", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۲-خراسان"],
            ["id" => "367", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۲-ری"],
            ["id" => "368", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۲-سعدی"],
            ["id" => "369", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۲-لاله زارنو"],
            ["id" => "370", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۲-مولوی"],
            ["id" => "371", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۲-مولوی"],
            ["id" => "372", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۳-صفا"],
            ["id" => "373", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۳-شهید اسدی"],
            ["id" => "374", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۳-زاهد گیلانی"],
            ["id" => "375", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۳-اشراقی"],
            ["id" => "376", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۳-دهقان"],
            ["id" => "377", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۳-نیروی هوایی"],
            ["id" => "378", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۳-پیروزی"],
            ["id" => "379", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۳-حافظیه"],
            ["id" => "380", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۳-امامت"],
            ["id" => "381", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۳-شورا"],
            ["id" => "382", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۳-آشتیانی"],
            ["id" => "383", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۳-زینبیه"],
            ["id" => "384", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۳-سرخه حصار"],
            ["id" => "385", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۳-تهران نو"],
            ["id" => "386", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۳-دماوند"],
            ["id" => "387", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۳-نیرو هوایی"],
            ["id" => "388", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-شکوفه"],
            ["id" => "389", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-چهارصد دستگاه"],
            ["id" => "390", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-جابری"],
            ["id" => "391", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-دژکام"],
            ["id" => "392", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-شاهین"],
            ["id" => "393", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-مینای شمالی"],
            ["id" => "394", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-نیکنام"],
            ["id" => "395", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-آهنگران"],
            ["id" => "396", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-بروجردی"],
            ["id" => "397", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-صد دستگاه"],
            ["id" => "398", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-فرزانه"],
            ["id" => "399", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-سر آسیب دولاب"],
            ["id" => "400", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-شیوا"],
            ["id" => "401", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-نبی اکرم (ص)"],
            ["id" => "402", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-شهرابی ( قیام )"],
            ["id" => "403", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-شکیب"],
            ["id" => "404", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-پرستار"],
            ["id" => "405", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-سیزده آبان"],
            ["id" => "406", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-ابوذر"],
            ["id" => "407", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-تاکسیرانی"],
            ["id" => "408", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-مینای جنوبی"],
            ["id" => "409", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-دولاب"],
            ["id" => "410", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-خاوران"],
            ["id" => "411", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-آهنگ شرقی"],
            ["id" => "412", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-آهنگ"],
            ["id" => "413", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-قصر فیروزه"],
            ["id" => "414", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-اتوبان محلاتی"],
            ["id" => "415", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-افراسیابی شمالی"],
            ["id" => "416", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-اندرزگو"],
            ["id" => "417", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-پاسدارگمنام"],
            ["id" => "418", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-شهید محلاتی"],
            ["id" => "419", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-فلاح"],
            ["id" => "420", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-نبرد"],
            ["id" => "421", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۴-هفده شهریور"],
            ["id" => "422", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۵-مظاهری"],
            ["id" => "423", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۵-مینابی"],
            ["id" => "424", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۵-بیسیم"],
            ["id" => "425", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۵-شوش"],
            ["id" => "426", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۵-طیب
            "],
            ["id" => "427", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۵-مطهری"],
            ["id" => "428", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۵-ابوذر"],
            ["id" => "429", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۵-هاشم آباد"],
            ["id" => "430", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۵-اتابک"],
            ["id" => "431", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۵-شهید بروجردی"],
            ["id" => "432", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۵-کیانشهر شمالی"],
            ["id" => "433", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۵-کیانشهر جنوبی"],
            ["id" => "434", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۵-رضویه"],
            ["id" => "435", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۵-مشیریه"],
            ["id" => "436", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۵افسریه شمالی-"],
            ["id" => "437", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۵-افسریه جنوبی"],
            ["id" => "438", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۵-مسعودیه"],
            ["id" => "439", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۵-والفجر"],
            ["id" => "440", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۵-قیامدشت"],
            ["id" => "441", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۵-خاورشهر"],
            ["id" => "442", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۵-آهنگ"],
            ["id" => "443", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۵-اتوبان بعثت"],
            ["id" => "444", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۵-افسریه"],
            ["id" => "445", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۵-خاوران"],
            ["id" => "446", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۵-مشیریه"],
            ["id" => "447", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۶-جوادیه"],
            ["id" => "448", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۶-نازی آباد"],
            ["id" => "449", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۶-خزانه"],
            ["id" => "450", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۶-شهرک بعثت"],
            ["id" => "451", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۶-علی آباد شمالی"],
            ["id" => "452", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۶-یاخچی آباد و چهارصد دستگاه"],
            ["id" => "453", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۶-تختی"],
            ["id" => "454", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۶-علی آباد جنوبی"],
            ["id" => "455", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۶-باغ آذری"],
            ["id" => "456", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۶-راه آهن"],
            ["id" => "457", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۶-رجایی"],
            ["id" => "458", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۶-هلال احمر"],
            ["id" => "459", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۶-یاخچی آباد"],
            ["id" => "460", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۷-ابوذر غربی"],
            ["id" => "461", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۷-آذری"],
            ["id" => "462", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۷-امامزاده حسن(ع)"],
            ["id" => "463", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۷-یافت آباد"],
            ["id" => "464", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۷-جلیلی"],
            ["id" => "465", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۷-زهتابی"],
            ["id" => "466", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۷-زمزم"],
            ["id" => "467", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۷-سجاد"],
            ["id" => "468", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۷-گلچین"],
            ["id" => "469", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۷-وصفنارد"],
            ["id" => "470", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۷-ابوذر شرقی"],
            ["id" => "471", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۷-باغ خزانه"],
            ["id" => "472", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۷-بلورسازی"],
            ["id" => "473", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۷-مقدم"],
            ["id" => "474", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۷-ابوذر"],
            ["id" => "475", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۷-امام زاده حسن"],
            ["id" => "476", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۷-قزوین"],
            ["id" => "477", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۷-قلعه مرغی"],
            ["id" => "478", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۷-میدان بهاران"],
            ["id" => "479", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۸-فردوس"],
            ["id" => "480", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۸-تولیدارو"],
            ["id" => "481", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۸-بهداشت"],
            ["id" => "482", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۸-ولیعصر شمالی"],
            ["id" => "483", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۸-رجائی"],
            ["id" => "484", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۸-ولیعصر جنوبی"],
            ["id" => "485", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۸-صادقیه"],
            ["id" => "486", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۸-صاحب الزمان"],
            ["id" => "487", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۸-یافت آباد جنوبی"],
            ["id" => "488", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۸-یافت آباد شمالی"],
            ["id" => "489", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۸-شاد آباد"],
            ["id" => "490", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۸-هفده شهریور"],
            ["id" => "491", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۸-امام خمینی (ره )"],
            ["id" => "492", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۸-شمس آباد"],
            ["id" => "493", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۸-خلیج فارس شمالی"],
            ["id" => "494", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۸-خلیج فارس جنوبی"],
            ["id" => "495", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۸-اتوبان آزادگان"],
            ["id" => "496", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۸-خلیج فارس"],
            ["id" => "497", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۸-سعید آباد"],
            ["id" => "498", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۸-شهرک صاحب الزمان"],
            ["id" => "499", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۸-شهرک ولیعصر"],
            ["id" => "500", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۹-خانی آباد نو شمالی"],
            ["id" => "501", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۹-اسفندیاری و بستان"],
            ["id" => "502", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۹-بهمنیار"],
            ["id" => "503", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۹-خانی آباد نو جنوبی"],
            ["id" => "504", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۹-شریعتی جنوبی"],
            ["id" => "505", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۹-شریعتی شمالی"],
            ["id" => "506", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۹-شکوفه جنوبی"],
            ["id" => "507", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۹-شکوفه شمالی"],
            ["id" => "508", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۹-نعمت آباد"],
            ["id" => "509", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۹-دولت خواه"],
            ["id" => "510", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۹-اسماعیل آباد"],
            ["id" => "511", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۹-شهید کاظمی"],
            ["id" => "512", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۹-رسالت"],
            ["id" => "513", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۹-خانی آباد نو"],
            ["id" => "514", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۱۹-عبدل آباد"],
            ["id" => "515", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۰-اقدسیه"],
            ["id" => "516", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۰-صفائیه"],
            ["id" => "517", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۰-ظهیر آباد"],
            ["id" => "518", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۰-غیوری"],
            ["id" => "519", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۰-جوانمرد"],
            ["id" => "520", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۰-حمزه آباد"],
            ["id" => "521", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۰-دیلمان"],
            ["id" => "522", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۰-دیلمان"],
            ["id" => "523", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۰-منصوریه"],
            ["id" => "524", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۰-13آبان"],
            ["id" => "525", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۰-دولت اباد"],
            ["id" => "526", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۰-شهادت"],
            ["id" => "527", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۰-استخر"],
            ["id" => "528", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۰-بهشتی"],
            ["id" => "529", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۰-سرتخت"],
            ["id" => "530", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۰-علائین"],
            ["id" => "531", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۰-نفر آباد"],
            ["id" => "532", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۰-ولی آباد"],
            ["id" => "533", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۰-امین آباد"],
            ["id" => "534", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۰-تقی آباد"],
            ["id" => "535", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۰-نظامی"],
            ["id" => "536", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۰-عباس آباد"],
            ["id" => "537", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۰-کهریزک"],
            ["id" => "538", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۱-شهرک دریا"],
            ["id" => "539", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۱-تهرانسر غربی"],
            ["id" => "540", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۱-تهرانسر شرقی"],
            ["id" => "541", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۱-باشگاه نفت"],
            ["id" => "542", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۱-تهرانسر مرکزی"],
            ["id" => "543", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۱-شهرک پاسداران"],
            ["id" => "544", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۱-تهرانسر شمالی"],
            ["id" => "545", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۱-شهرک آزادی"],
            ["id" => "546", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۱-شهرک فرهنگیان"],
            ["id" => "547", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۱-شهرک استقلال"],
            ["id" => "548", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۱-شهرک دانشگاه"],
            ["id" => "549", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۱-چیتگر شمالی"],
            ["id" => "550", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۱-چیتگر جنوبی (شهرک 22 بهمن)"],
            ["id" => "551", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۱-ویلا شهر"],
            ["id" => "552", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۱-وردآورد"],
            ["id" => "553", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۱-شهرک غزالی"],
            ["id" => "554", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۱-شهرک شهرداری"],
            ["id" => "555", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۱-اتوبان تهران کرج"],
            ["id" => "556", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۱-بزرگراه فتح"],
            ["id" => "557", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۱-تهرانسر"],
            ["id" => "558", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۱-شهرک 22بهمن"],
            ["id" => "559", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۱-شهرک دانشگاه شریف"],
            ["id" => "560", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۲-کوهک"],
            ["id" => "561", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۲-دهکده المپیک"],
            ["id" => "562", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۲-زیبا دشت بالا"],
            ["id" => "563", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۲-گلستان شرقی"],
            ["id" => "564", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۲-زیبادشت پائین"],
            ["id" => "565", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۲-شریف"],
            ["id" => "566", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۲-گلستان غربی"],
            ["id" => "567", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۲-امید - دژبان"],
            ["id" => "568", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۲-شهید باقری"],
            ["id" => "569", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۲-آزادشهر"],
            ["id" => "570", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۲-پیکان شهر"],
            ["id" => "571", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۲-دریاچه چیتگر"],
            ["id" => "572", "province_id" => 8, "city_id" => 126, "name" => "منطقه ۲۲-شهرک گلستان (شهرک راه آهن)"],
        ];

        $insert = array_map(function ($district) {
            $district['created_at'] = now();
            $district['updated_at'] = now();
            return $district;
        }, $districts);

        District::insert($insert);
    }
}
